//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponentScore()
        {
            this.DetailScore = new HashSet<DetailScore>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get; set; }
        public string DisplayName { get; set; }
        public Nullable<double> ContributePercent { get; set; }
    
        public virtual SubjectClass SubjectClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailScore> DetailScore { get; set; }
    }
}
