//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentManagementEntities : DbContext
    {
        public StudentManagementEntities()
            : base("name=StudentManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsentCalendar> AbsentCalendar { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ComponentScore> ComponentScore { get; set; }
        public virtual DbSet<CourseRegister> CourseRegister { get; set; }
        public virtual DbSet<DatabaseImageTable> DatabaseImageTable { get; set; }
        public virtual DbSet<DetailScore> DetailScore { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Faculty_TrainingForm> Faculty_TrainingForm { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NotificationComment> NotificationComment { get; set; }
        public virtual DbSet<NotificationImages> NotificationImages { get; set; }
        public virtual DbSet<NotificationInfo> NotificationInfo { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<OTP> OTP { get; set; }
        public virtual DbSet<Security> Security { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectClass> SubjectClass { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TrainingForm> TrainingForm { get; set; }
        public virtual DbSet<TrainingScore> TrainingScore { get; set; }
        public virtual DbSet<User_UserRole_UserInfo> User_UserRole_UserInfo { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRole_UserInfo> UserRole_UserInfo { get; set; }
        public virtual DbSet<UserRole_UserInfoItem> UserRole_UserInfoItem { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
