//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.NotificationInfo = new HashSet<NotificationInfo>();
            this.NotificationComment = new HashSet<NotificationComment>();
            this.NotificationImages = new HashSet<NotificationImages>();
        }
    
        public System.Guid Id { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.Guid> IdNotificationType { get; set; }
        public Nullable<System.Guid> IdPoster { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationInfo> NotificationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationComment> NotificationComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationImages> NotificationImages { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual SubjectClass SubjectClass { get; set; }
        public virtual SubjectClass SubjectClass1 { get; set; }
    }
}
