//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.CourseRegister = new HashSet<CourseRegister>();
            this.DetailScore = new HashSet<DetailScore>();
            this.TrainingScore = new HashSet<TrainingScore>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdTrainingForm { get; set; }
        public Nullable<System.Guid> IdFaculty { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> IdUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegister> CourseRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailScore> DetailScore { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual TrainingForm TrainingForm { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingScore> TrainingScore { get; set; }
		public string Username { get; internal set; }
	}
}
