//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRole_UserInfo()
        {
            this.User_UserRole_UserInfo = new HashSet<User_UserRole_UserInfo>();
            this.UserRole_UserInfoItem = new HashSet<UserRole_UserInfoItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRole { get; set; }
        public string InfoName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserRole_UserInfo> User_UserRole_UserInfo { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole_UserInfoItem> UserRole_UserInfoItem { get; set; }
    }
}
