//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_UserInfoItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdUserRole_Info { get; set; }
        public string Content { get; set; }
    
        public virtual UserRole_UserInfo UserRole_UserInfo { get; set; }
    }
}
